### ISSUE TITLE
Error while building the Widget

### ISSUE THREAD

**Issue by GENL** [JeffG05/emoji_picker#17]
That is the error I get when building EmojiPicker widget: 
```
Error caught by Crashlytics plugin <recordError>:
I/flutter ( 7351): MissingPluginException(No implementation found for method isAvailable on channel emoji_picker)
I/flutter ( 7351): 
I/flutter ( 7351): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter ( 7351): <asynchronous suspension>
I/flutter ( 7351): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter ( 7351): #2      _EmojiPickerState._isEmojiAvailable (package:emoji_picker/emoji_picker.dart:322:28)
I/flutter ( 7351): #3      _EmojiPickerState.getAvailableEmojis (package:emoji_picker/emoji_picker.dart:356:32)
I/flutter ( 7351): #4      _EmojiPickerState.updateEmojis (package:emoji_picker/emoji_picker.dart:366:23)
I/flutter ( 7351): #5      _EmojiPickerState.initState (package:emoji_picker/emoji_picker.dart:312:5)
I/flutter ( 7351): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4461:58)
I/flutter ( 7351): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 7351): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 7351): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 7351): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5575:14)
I/flutter ( 7351): #11     Element.i
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [version 10.0.18362.592], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.39.2)
[√] Connected device (3 available)

• No issues found!

```

**Comment by GENL** [comment]
The app now crashes. Can you please update it for it works with both the last flutter version and androidX? As you say in comment in `EmojiPickerPlugin.java` it does not use support post-flutter-1.12 projects.
Thanks.

**Comment by jenniestrongbow** [comment]
Same problem
